# Generated by Django 4.0.4 on 2022-05-04 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='manufacturer',
            table='Manufacturer',
        ),
    ]
